### ISSUE TITLE
Does MMKV implement custom encryption?

### ISSUE THREAD

**Issue by LukasHechenberger** [Tencent/MMKV#1216]
For my iOS app I need to know if MMKV uses encryption not built into the OS (`ITSAppUsesNonExemptEncryption` inside Info.plist).

[Apple Documentation](https://developer.apple.com/help/app-store-connect/manage-app-information/detemine-and-upload-export-compliance-documentation)

**Comment by lingol** [comment]
1. >if MMKV uses encryption not built into the OS 

    Yes. https://github.com/Tencent/MMKV/wiki/FAQ
    >What kind of encryption algorithm does MMKV use?
MMKV uses AES CFB-128 for encryption and decryption, using OpenSSL's implementation (version 1.1.0i). We choose CFB instead of widely used CBC, mainly because MMKV implements insert/update by an append-only operation. Stream encryption algorithms like CFB are more suitable.

2. But it's off by default. You have to use the encryption interface. https://github.com/Tencent/MMKV/wiki/iOS_advance#encryption

**Comment by LukasHechenberger** [comment]
Thanks a lot, @lingol!

**Comment by lingol** [comment]
MMKV v2.3.0 provides AES-256 key length. http://github.com/Tencent/mmkv/releases/tag/v2.3.0
