### ISSUE TITLE
crc 校验失败，或者文件长度不对的时候，MMKV 默认会丢弃所有数据

### ISSUE THREAD

**Issue by chdzq** [Tencent/MMKV#259]
### The language of MMKV

Object-C

### The version of MMKV

 v1.0.18

### The platform of MMKV

 iOS

### The installation of MMKV

 Cocoapods

### What's the issue?
我认真看了下源码及wiki，发现「在 crc 校验失败，或者文件长度不对的时候，MMKV 默认会丢弃所有数据。」源码也确实这么做的，所以有两点疑问：1、如果校验失败，是不是可以不全部清除数据？2、可不可以计算出来了每一个append的数据的crc校验码，然后存下来，在loadFromFile时候对每一个数据校验，只删除校验不通过的数据。
 希望能解答下疑问。谢谢。
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
I believe you has miss something in the code. MMKV support recover (on demand) since [v1.0.13](https://github.com/Tencent/MMKV/releases/tag/v1.0.13).

**Comment by chdzq** [comment]
yes, u are right. but i also think the better is check crc code for each data, so we can decide which can stay. otherwise, the crc is meaningless  when we decide to recover data by delegate .

**Comment by lingol** [comment]
OK. Now it comes to a trade-off decision making. Your point is understandable, yet cost too much storage consumption & increase code complexity. And too much work to consider for file format upgrading at this point, since the origin mmkv is already widely used today.

You are very welcome to implement one on top of MMKV yourself, though.

**Comment by chdzq** [comment]
Thanks your answer. The truth is as you said.
