### ISSUE TITLE
使用mmkvWithAshmemID主进程挂掉后如何恢复？

### ISSUE THREAD

**Issue by tangxiangpi** [Tencent/MMKV#283]
首先我是用mmkv demo工程做的测试。
在mmkvdemo进程中使用mmkvWithAshmemID创建一个mmkv实例，
然后使用
Intent intent = new Intent(this, MyService.class);
        intent.putExtra(BenchMarkBaseService.CMD_ID, BenchMarkBaseService.CMD_PREPARE_ASHMEM_BY_CP);
        startService(intent);

        intent = new Intent(this, MyService_1.class);
        intent.putExtra(BenchMarkBaseService.CMD_ID, BenchMarkBaseService.CMD_PREPARE_ASHMEM_BY_CP);
        startService(intent);
在两个service进程中同样创建了mmkv实例，这时候测试主进程写一个key的值，两个service进程读取key的值是对的。

但是如果我从android stuido控制台杀掉mmkvdemo进程（两个service进程还在），再打开app进行同样的上述流程，我发现其实主进程的mmkv实例和两个服务进程的mmkv实例映射的不是同一块内存地址了，主进程修改key的值，服务进程读取还是旧的。

如何能够恢复正常，使这几个进程的mmkv映射到同一个地方？因为android系统的原因，对于多进程应用来说，主进程在后台被杀是很正常的现象，我发现了这个问题，所以暂时用文件存储的mmkv替代了ashemmmkv的使用。

**Comment by tangxiangpi** [comment]
反过来，我用控制台杀掉一个service进程，因为service进程会重启，同样的代码流程却是正常的。

**Comment by tangxiangpi** [comment]
经过测试，主进程杀掉的情况，我在service进程中判断之前的mmkv实例在的话就先调用close方法，再调用mmkvWithAshmemID初始化就是正常的，请问这是什么原因？
再有MMKV里面的那些方法可否增加文档，不知道具体api的作用，只能挨个试

**Comment by tangxiangpi** [comment]
这样有个弊端，假如我缓存了100个key，如果主进程挂了，那么重新初始化mmkv，这些key都没有了。而实际上service进程的mmkv还有这100个key，有没有办法在主进程初始化的时候关联到service进程的那个mmkv对象映射的内存？？

**Comment by lingol** [comment]
> 经过测试，主进程杀掉的情况，我在service进程中判断之前的mmkv实例在的话就先调用close方法，再调用mmkvWithAshmemID初始化就是正常的，请问这是什么原因？
> 再有MMKV里面的那些方法可否增加文档，不知道具体api的作用，只能挨个试

That's almost right.
Due to the Android OS limitation, when the process which has created the ashmem is killed, there's no way to bring it back. When the process restarts, a new ashmem is created even if we pass the same id.
So, the right procedure, when the main process restarts, is for those service processes to dump the old ashmem mmkv, and get a new one by calling `mmkvWithAshmemID()` again.

Sorry for the lack of documentation on ashmem MMKV, will make it more clear in the future.

**Comment by lingol** [comment]
> 这样有个弊端，假如我缓存了100个key，如果主进程挂了，那么重新初始化mmkv，这些key都没有了。而实际上service进程的mmkv还有这100个key，有没有办法在主进程初始化的时候关联到service进程的那个mmkv对象映射的内存？？

NO way to do that.

**Comment by tangxiangpi** [comment]
> > 这样有个弊端，假如我缓存了100个key，如果主进程挂了，那么重新初始化mmkv，这些key都没有了。而实际上service进程的mmkv还有这100个key，有没有办法在主进程初始化的时候关联到service进程的那个mmkv对象映射的内存？？
> 
> NO way to do that.

谢谢回复，这样看匿名内存共享能够使用的场景可能就比较有局限性了，本身使用内存共享就是不希望和进程间通信打交道，但是如果想很好地使用匿名内存共享却需要关心这些细节，特别是android这样的进程被杀的情况各种各样，一不小心就掉坑里去了，还是用mmap文件靠谱一些了
