### ISSUE TITLE
在unity项目中集成时会造成unity加载资源的代码crash

### ISSUE THREAD

**Issue by c344081** [Tencent/MMKV#471]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
Objective-C

### The version of MMKV

> e.g. v1.0.10
1.0.23

### The platform of MMKV

> e.g. iOS or Android
iOS

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?
unity 使用AssetBundle.LoadFromMemoryAsync时crash, 移除MMKV后正常
![image](https://user-images.githubusercontent.com/9611943/84397886-ccf1e000-ac31-11ea-8807-b3f1bc9d9c38.png)
![image](https://user-images.githubusercontent.com/9611943/84397911-d4b18480-ac31-11ea-87bf-6ced2ddc29be.png)

**Comment by lingol** [comment]
The crash stacks and logs please.

**Comment by lingol** [comment]
Upgrade to v1.1.2.

**Comment by lingol** [comment]
I'll explain a little more. The crash symbols from Unity looks like the code from the `dev_bigfile` branch. Someone inside Unity just copies my code without telling me. Which is fine because MMKV is an opensource project. But at least they should handle symbol confliction better, add a namespace or something.

**Comment by c344081** [comment]
非常感谢，升级到1.1.2后可以正常加载资源了，我的unity版本是2019.2.14f1
