### ISSUE TITLE
How to disable mmkv default folder creation in users documents dicrectory, aka ~/Documents

### ISSUE THREAD

**Issue by Sunnyyoung** [Tencent/MMKV#474]
### The language of MMKV

Swift

### The version of MMKV

v1.1.2

### The platform of MMKV

macOS

### The installation of MMKV

Cocoapods

### What's the issue?

https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/libMMKV.mm#L64

How to disable mmkv default folder creation in users documents dicrectory, aka ~/Documents, which may make user annoying 🤔

**Comment by lingol** [comment]
You should sandbox your app.

**Comment by lingol** [comment]
https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html

**Comment by Sunnyyoung** [comment]
What if I need privileges elevation https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html, which needs to be set to non-sanbox environment.

**Comment by lingol** [comment]
Then you gonna set the root dir of MMKV.
https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/libMMKV.mm#L84

**Comment by Sunnyyoung** [comment]
According to the `mmkv::MMKV::minimalInit` called from `+ (void)initialize`, mmkv default folder will be created in any cases.

**Comment by lingol** [comment]
Oh sorry, that's true. That piece of code is necessary for backward compatibility, so that's no way to make it optional.
I'm afraid you don't have much choice here. You can either  
1. Make a [patch locally](https://stackoverflow.com/questions/16821838/how-to-patch-a-library-imported-with-cocoapods) for your project, or
2. Split your privileges code into a separate [helper tool](https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html#//apple_ref/doc/uid/TP40002589-SW2), and keep your main App sandboxed.
