### ISSUE TITLE
got an error: Opening a single-process MMKV instance with MULTI_PROCESS_MODE!

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#513]
Android mmkv 1.2.2

I got an IllegalArgumentException with the following error message.
**Opening a single-process MMKV instance [comm] with MULTI_PROCESS_MODE!**
 
I am sure that I always open the "comm" mmkv with MULTI_PROCESS_MODE.
`MMKV mmkv = MMKV.mmkvWithID("comm", MMKV.MULTI_PROCESS_MODE, null, null);
`

I also noticed a mmkv error log:
**ERR MMKV_Android.cpp:230::checkProcessMode: Fail to exclusive lock [comm]**

Please note that it's not the case of opening a shared mmkv with SINGLE_PROCESS_MODE.
Initially, the "comm" mmkv is opened by a process A and we may open the same "comm" mmkv later in process B.
That's why we always open "comm" mmkv with the MULTI_PROCESS_MODE flag but why it shows us the error saying we cannot open it with MULTI_PROCESS_MODE?

**Comment by lingol** [comment]
Full logs of mmkv please. Including both process A&B.

**Comment by samlu** [comment]
We cannot reproduce this problem on our devices.
The crashlytics shows that 60% of errors happen on Android 10 and the disk free size is more than 10GB.

**Comment by samlu** [comment]
The only mmkv log of process A is 
**ERR MMKV_Android.cpp:230::checkProcessMode: Fail to exclusive lock [comm]**

Process B is not started so no mmkv logs.

**Comment by samlu** [comment]
I don't see any code added to this issue. 
Would you help to note why you close this ticket?

**Comment by lingol** [comment]
It's a duplication.

**Comment by samlu** [comment]
Just to remind you that this ticket is not exactly the same as #515 as:
1. it happens when opening a mmkv with MULTI_PROCESS_MODE
2. no mmkv erros before **ERR MMKV_Android.cpp:230::checkProcessMode: Fail to exclusive lock [comm]**

**Comment by lingol** [comment]
It's impossible for a process to have that one and only one line of MMKV's log. So I have to assume it's duplicated unless you have more info to add.

**Comment by lingol** [comment]
Made it much clear about this exception on the dev branch. You might check it out.

**Comment by siyehua** [comment]
可以肯定我也没有使用单进程的方式打开, 但是提示 carsh 了, 正常情况下无法复现, 但是在 crash 手机平台有很多上报.
我用了 1.2.5 的版本, 但还有解决这个问题, 发生时的日志

`
12-19 03:14:06.722 E/anager:transmi(22066): Not starting debugger since process cannot load the jdwp agent.
12-19 03:14:07.224 E/MMKV    (22066): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv]
--------- beginning of crash
`

捕捉的日志只有这么多, 后面就 crash 了 @lingol

**Comment by lingol** [comment]
> 可以肯定我也没有使用单进程的方式打开, 但是提示 carsh 了, 正常情况下无法复现, 但是在 crash 手机平台有很多上报.
> 我用了 1.2.5 的版本, 但还有解决这个问题, 发生时的日志
> 
> `12-19 03:14:06.722 E/anager:transmi(22066): Not starting debugger since process cannot load the jdwp agent. 12-19 03:14:07.224 E/MMKV (22066): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv] --------- beginning of crash`
> 
> 捕捉的日志只有这么多, 后面就 crash 了 @lingol

According to the logs, looks like there's another process that has opened the MMKV instance with single-process mode.
You might check if that's possible.

By the way, you should collect logs from **all processes, from the point MMKV is initialized on each process**.

**Comment by siyehua** [comment]
> > 可以肯定我也没有使用单进程的方式打开, 但是提示 carsh 了, 正常情况下无法复现, 但是在 crash 手机平台有很多上报.
> > 我用了 1.2.5 的版本, 但还有解决这个问题, 发生时的日志
> > `12-19 03:14:06.722 E/anager:transmi(22066): Not starting debugger since process cannot load the jdwp agent. 12-19 03:14:07.224 E/MMKV (22066): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv] --------- beginning of crash`
> > 捕捉的日志只有这么多, 后面就 crash 了 @lingol
> 
> According to the logs, looks like there's another process that has opened the MMKV instance with single-process mode.
> You might check if that's possible.
> 
> By the way, you should collect logs from **all processes, from the point MMKV is initialized on each process**.

完整的日志没有更多的信息:

`12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.tencent.mmkv.MMKV.a(MMKV.java:283)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.tencent.mmkv.MMKV.a(MMKV.java:167)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.a.f(AbsSharedPreferencesHelper.java:105)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.a.<init>(AbsSharedPreferencesHelper.java:41)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.net.b.c.a.<init>(SharkDao.java:55)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.net.b.c.a.a(SharkDao.java:63)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.net.b.d.d.d(SharkOutlet.java:140)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.impl.e.b(SourceFile:80)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.impl.e.<init>(SourceFile:58)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.impl.h.<init>(SourceFile:854)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.impl.j.a(SourceFile:1138)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.api.s$1.run(SourceFile:87)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at com.xxx.xxx.util.d.h$a.run(CustomThreadPool.java:1154)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-19 08:46:36.176 E/AndroidRuntime(13186): 	at java.lang.Thread.run(Thread.java:919)
12-19 08:46:36.183 E/lerymanager:mo(13186): No implementation found for void com.xxx.xxx.database.SQLiteGlobal.nativeTestJNIRegistration() (tried Java_com_tencent_wcdb_database_SQLiteGlobal_nativeTestJNIRegistration and Java_com_tencent_wcdb_database_SQLiteGlobal_nativeTestJNIRegistration__)
12-19 08:46:36.231 E/MMKV    (13207): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv]
12-19 08:46:36.248 E/AndroidRuntime(13207): FATAL EXCEPTION: main
12-19 08:46:36.248 E/AndroidRuntime(13207): Process: com.xxx.xxx:transmit, PID: 13207
12-19 08:46:36.248 E/AndroidRuntime(13207): java.lang.RuntimeException: Unable to create application com.xxx.xxx.GalleryAppLike: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6890)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.app.ActivityThread.access$1600(ActivityThread.java:255)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.os.Looper.loop(Looper.java:230)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.app.ActivityThread.main(ActivityThread.java:7815)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at java.lang.reflect.Method.invoke(Native Method)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
12-19 08:46:36.248 E/AndroidRuntime(13207): Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:104)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(TinkerApplicationInlineFence.java:110)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:153)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.GalleryAppLike.onCreate(Unknown Source:3)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1236)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6885)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	... 8 more
12-19 08:46:36.248 E/AndroidRuntime(13207): Caused by: java.lang.IllegalArgumentException: Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.tencent.mmkv.MMKV.a(MMKV.java:283)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.tencent.mmkv.MMKV.a(MMKV.java:167)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.a.a.f(AbsSharedPreferencesHelper.java:105)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.a.a.<init>(AbsSharedPreferencesHelper.java:53)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.d.i.<init>(SharedPreferencesHelper.java:16)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.d.i.c(SharedPreferencesHelper.java:23)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.a.b$a.a(ColorLogConfig.kt:61)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.a.b.e(Unknown Source:2)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.a.c.a(ColorLogController.java:29)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.a.a.a(ColorLog.kt:106)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.m.a.c$m.a(LowTask.kt:72)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.m.a.c$m.invoke(LowTask.kt:44)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.m.b.c.b(InitTask.kt:206)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.m.b.b.b(InitTask.kt:132)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.m.b.b.a(InitTask.kt:107)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.c.d(GalleryApp.java:75)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.xxx.xxx.GalleryAppLikeProxy.onCreate(GalleryAppLikeProxy.java:84)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:99)
12-19 08:46:36.248 E/AndroidRuntime(13207): 	... 13 more
12-19 08:46:36.314 E/MMKV    (13186): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv]
12-19 08:46:36.316 E/AndroidRuntime(13186): FATAL EXCEPTION: main
12-19 08:46:36.316 E/AndroidRuntime(13186): Process: com.xxx.xxx:mon, PID: 13186
12-19 08:46:36.316 E/AndroidRuntime(13186): java.lang.RuntimeException: Unable to create application com.xxx.xxx.GalleryAppLike: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6890)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.app.ActivityThread.access$1600(ActivityThread.java:255)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.os.Looper.loop(Looper.java:230)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.app.ActivityThread.main(ActivityThread.java:7815)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at java.lang.reflect.Method.invoke(Native Method)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
12-19 08:46:36.316 E/AndroidRuntime(13186): Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:104)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(TinkerApplicationInlineFence.java:110)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:153)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.GalleryAppLike.onCreate(Unknown Source:3)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1236)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6885)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	... 8 more
12-19 08:46:36.316 E/AndroidRuntime(13186): Caused by: java.lang.IllegalArgumentException: Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.tencent.mmkv.MMKV.a(MMKV.java:283)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.tencent.mmkv.MMKV.a(MMKV.java:167)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.a.f(AbsSharedPreferencesHelper.java:105)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.a.<init>(AbsSharedPreferencesHelper.java:53)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.d.i.<init>(SharedPreferencesHelper.java:16)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.d.i.c(SharedPreferencesHelper.java:23)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.b$a.a(ColorLogConfig.kt:61)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.b.e(Unknown Source:2)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.c.a(ColorLogController.java:29)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.a.a.a(ColorLog.kt:106)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.m.a.c$m.a(LowTask.kt:72)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.m.a.c$m.invoke(LowTask.kt:44)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.m.b.c.b(InitTask.kt:206)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.m.b.b.b(InitTask.kt:132)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.m.b.b.a(InitTask.kt:107)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.c.d(GalleryApp.java:75)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.xxx.xxx.GalleryAppLikeProxy.onCreate(GalleryAppLikeProxy.java:84)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:99)
12-19 08:46:36.316 E/AndroidRuntime(13186): 	... 13 more
12-19 08:46:36.624 E/libc    (13290): Access denied finding property "ro.vendor.net.upload.benchmark.default"`


打开 MMKV 的时候, 使用的是我自定义的类: AbsSharedPreferencesHelper, 其中关键实现是:
`   public AbsSharedPreferencesHelper() {
        mSetting = MMKV.mmkvWithID(DEFAULT_NAME, MMKV.MULTI_PROCESS_MODE);
    }
`

这个默认的 DEFAULT_NAME, 就是 default_name_mmkv, 除了这里, 整个项目就再也没有其他地方使用 default_name_mmkv 这个字符串, 更不要说用它来打开 MMKV 了

**Comment by lingol** [comment]
Nan, MMKV's initialization log is not shown. You must have missed some logs.

**Comment by lingol** [comment]
If I were you, I won't be so sure about no others getting `default_name_mmkv` with single-process mode. You should **check logs for evidence** of other processed opening `default_name_mmkv` with single-process mode. 

I'm sure there will be some logs about it. That why I'm insisting on posting **all logs of all processes**.

**Comment by siyehua** [comment]
> MMKV's initialization log is not shown. You must have missed some logs.

日志捕捉平台不是很强大, 只能抓到 carsh 的一刹那的时候,有的时候还不全, 我查所有的 crash 有找到一个日志稍微全一点的, 多了几行mmvk cpp 的打印, 不过依旧没有初始化的信息. 


```
12-18 20:22:58.654 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:22:59.536 I/CtrlSocket(28941): connect skiped
12-18 20:22:59.568 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:22:59.655 I/CtrlSocket(28941): connect skiped
12-18 20:23:00.069 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:23:00.570 I/CtrlSocket(28941): connect skiped
12-18 20:23:00.570 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:23:01.071 I/CtrlSocket(28941): connect skiped
12-18 20:23:01.072 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:23:01.572 I/CtrlSocket(28941): connect skiped
12-18 20:23:01.600 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:23:02.072 I/CtrlSocket(28941): connect skiped
12-18 20:23:05.338 I/CtrlSocket(28941): connect skiped
12-18 20:23:05.338 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:23:05.344 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:25.367 I/CtrlSocket(28941): connect skiped
12-18 20:24:25.367 I/CtrlSocket(28941): connect skiped
12-18 20:24:25.511 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:25.997 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:26.512 I/CtrlSocket(28941): connect skiped
12-18 20:24:26.512 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:26.998 I/CtrlSocket(28941): connect skiped
12-18 20:24:26.999 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:27.514 I/CtrlSocket(28941): connect skiped
12-18 20:24:27.544 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:28.000 I/CtrlSocket(28941): connect skiped
12-18 20:24:28.004 I/WM-WorkerWrapper(28941): Worker result RETRY for Work [ id=ffb2bc71-ceea-4975-a7ac-f2bf90ccff7e, tags={ com.xxx.xxx.service.ReportWorker } ]
12-18 20:24:30.412 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:24:30.488 I/CtrlSocket(28941): connect skiped
12-18 20:24:30.489 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:25:24.594 I/EP_SharkServiceProxy(28941): sendShark
12-18 20:25:24.604 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:25:25.116 W/WM-WorkSpec(28941): Backoff delay duration less than minimum value
12-18 20:25:25.218 I/WM-WorkerWrapper(28941): Worker result SUCCESS for Work [ id=37f05888-4c2a-4b46-9d8d-d3545989faee, tags={ com.xxx.xxx.cloudconfig.cloudcmd.business.manager.CloudCmdCommonWorker } ]
12-18 20:25:25.223 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:25:25.231 I/System  (28941): core_booster, getBoosterConfig = false
12-18 20:25:25.243 W/Tinker.TinkerLoader(29433): tryLoadPatchFiles:patch info not exist:/data/user/0/com.xxx.xxx/tinker/patch.info
12-18 20:25:25.250 I/MultiDex(29433): VM with version 2.1.0 has multidex support
12-18 20:25:25.250 I/MultiDex(29433): Installing application
12-18 20:25:25.250 I/MultiDex(29433): VM has multidex support, MultiDex support library is disabled.
12-18 20:25:25.269 I/MMKV    (29433): <native-bridge.cpp:103::JNI_OnLoad> current API level = 23
12-18 20:25:25.269 I/MMKV    (29433): <MMKV.cpp:156::initialize> version v1.2.5 page size:4096
12-18 20:25:25.269 I/MMKV    (29433): <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/com.xxx.xxx/files/mmkv
12-18 20:25:25.285 W/Tinker.Tinker(29433): tinker patch directory: /data/user/0/com.xxx.xxx/tinker
12-18 20:25:25.286 I/Tinker.Tinker(29433): try to install tinker, isEnable: true, version: 1.9.14.3
12-18 20:25:25.287 I/Tinker.TinkerLoadResult(29433): parseTinkerResult loadCode:-3, process name:com.xxx.xxx:mon, main process:false, systemOTA:false, fingerPrint:HUAWEI/MLA-AL10/HWMLA:6.0/HUAWEIMLA-AL10/C00B180:user/release-keys, oatDir:null, useInterpretMode:false
12-18 20:25:25.287 W/Tinker.TinkerLoadResult(29433): can't find patch file, is ok, just return
12-18 20:25:25.287 I/Tinker.DefaultLoadReporter(29433): patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -3, cost: 2ms
12-18 20:25:25.287 W/Tinker.Tinker(29433): tinker load fail!
12-18 20:25:25.291 I/Tinker.ComponentHotplug(29433): method install() is not invoked, ignore ensuring operations.
12-18 20:25:25.441 I/native_eup(29433): native library loaded
12-18 20:25:25.441 I/native_eup(29433): register native log methods success
12-18 20:25:25.441 I/native_eup(29433): register native key-value methods success
12-18 20:25:25.441 I/native_eup(29433): register native methods success
12-18 20:25:25.451 I/native_eup(29433): loglevel :23
12-18 20:25:25.453 I/System.out(29433): [/system/bin/sh, -c, getprop ro.board.platform]
12-18 20:25:25.453 I/System.out(29433): null
12-18 20:25:25.453 I/System.out(29433): null
12-18 20:25:25.453 I/System.out(29433): Calling by::className:com.xxx.xxx.b.u  MethodName:a
12-18 20:25:25.489 I/MMKV    (29433): <MMKV_IO.cpp:81::loadFromFile> loading [default_name_mmkv] with 437 actual size, file size 4096, InterProcess 1, meta info version:3
12-18 20:25:25.489 I/MMKV    (29433): <MMKV_IO.cpp:86::loadFromFile> loading [default_name_mmkv] with crc 1839047041 sequence 1 version 3
12-18 20:25:25.489 I/MMKV    (29433): <MMKV_IO.cpp:130::loadFromFile> loaded [default_name_mmkv] with 13 key-values
12-18 20:25:25.489 E/MMKV    (29433): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv]
12-18 20:25:25.492 I/ThreadPoolServiceProxy(29433): newFreeHandlerThread
12-18 20:25:25.494 I/ThreadPoolServiceProxy(29433): addTask
12-18 20:25:25.497 W/System.err(29433): java.lang.IllegalArgumentException: (Pv_none;Activity_null)Opening a MMKV instance [default_name_mmkv] with MULTI_PROCESS_MODE, while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!
12-18 20:25:25.497 W/System.err(29433): 	at com.tencent.mmkv.MMKV.a(MMKV.java:283)
12-18 20:25:25.497 W/System.err(29433): 	at com.tencent.mmkv.MMKV.a(MMKV.java:167)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.a.a.f(AbsSharedPreferencesHelper.java:105)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.a.a.<init>(AbsSharedPreferencesHelper.java:41)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.net.b.c.a.<init>(SharkDao.java:55)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.net.b.c.a.a(SharkDao.java:63)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.net.b.d.d.d(SharkOutlet.java:140)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.impl.e.b(SourceFile:80)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.impl.e.<init>(SourceFile:58)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.impl.h.<init>(SourceFile:854)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.impl.j.a(SourceFile:1138)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.api.s$1.run(SourceFile:87)
12-18 20:25:25.497 W/System.err(29433): 	at com.xxx.xxx.util.d.h$a.run(CustomThreadPool.java:1154)
12-18 20:25:25.498 W/System.err(29433): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-18 20:25:25.498 W/System.err(29433): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-18 20:25:25.498 W/System.err(29433): 	at java.lang.Thread.run(Thread.java:833)
12-18 20:25:25.501 I/System.out(29433): [/system/bin/sh, -c, type su]
12-18 20:25:25.501 I/System.out(29433): null
12-18 20:25:25.501 I/System.out(29433): null
12-18 20:25:25.501 I/System.out(29433): Calling by::className:com.xxx.xxx.b.u  MethodName:a
12-18 20:25:25.511 E/art     (29433): No implementation found for void com.xxx.xxx.database.SQLiteGlobal.nativeTestJNIRegistration() (tried Java_com_tencent_wcdb_database_SQLiteGlobal_nativeTestJNIRegistration and Java_com_tencent_wcdb_database_SQLiteGlobal_nativeTestJNIRegistration__)
12-18 20:25:25.557 E/MMKV    (29433): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv]
12-18 20:25:25.576 I/System.out(29433): [/system/bin/sh, -c, getprop ro.miui.ui.version.name]
12-18 20:25:25.576 I/System.out(29433): null
12-18 20:25:25.576 I/System.out(29433): null
12-18 20:25:25.577 I/System.out(29433): Calling by::className:com.xxx.xxx.b.u  MethodName:a
12-18 20:25:25.613 I/System.out(29433): [/system/bin/sh, -c, getprop ro.build.version.emui]
12-18 20:25:25.613 I/System.out(29433): null
12-18 20:25:25.613 I/System.out(29433): null
12-18 20:25:25.613 I/System.out(29433): Calling by::className:com.xxx.xxx.b.u  MethodName:a
12-18 20:25:25.925 I/System.out(29433): [logcat, -d, -v, time]
12-18 20:25:25.925 I/System.out(29433): null
12-18 20:25:25.925 I/System.out(29433): null
12-18 20:25:25.926 I/System.out(29433): Calling by::className:com.xxx.xxx.b.u  MethodName:a
```

关于被进程使用单进程模式打开的, 我确实查了很多遍, 项目里没有找到. 目前的办法是增加所有打开 mmkv 的日志, 增加埋点

**Comment by lingol** [comment]
That's better. But it only logs from the crashed process. You need logs of the process run & open `default_name_mmkv` before the crashed process.

**Comment by lzchengmi** [comment]
i found this crash on my own device ,but only once,  has this problem fixed?

**Comment by lingol** [comment]
> i found this crash on my own device ,but only once, has this problem fixed?

Well, where're your own logs?

**Comment by lzchengmi** [comment]
> > i found this crash on my own device ,but only once, has this problem fixed?
> 
> Well, where're your own logs?

well， when it happends  i just keep java‘s crash stack as follow：
![image](https://user-images.githubusercontent.com/68270788/103514611-f1502b00-4ea7-11eb-977d-508b97f443d8.png)

**Comment by lzchengmi** [comment]
> > > i found this crash on my own device ,but only once, has this problem fixed?
> > 
> > 
> > Well, where're your own logs?
> 
> well， when it happends i just keep java‘s crash stack as follow：
> ![image](https://user-images.githubusercontent.com/68270788/103514611-f1502b00-4ea7-11eb-977d-508b97f443d8.png)

and in my code，i never use any private mode， all acess to MMKV is multi-process

**Comment by lingol** [comment]
> > > i found this crash on my own device ,but only once, has this problem fixed?
> > 
> > 
> > Well, where're your own logs?
> 
> well， when it happends i just keep java‘s crash stack as follow：
> ![image](https://user-images.githubusercontent.com/68270788/103514611-f1502b00-4ea7-11eb-977d-508b97f443d8.png)

No, I mean **LOGS**, not call stacks.

**Comment by lzchengmi** [comment]
i cannot get logs any more；it is long ago and cannot reproduce。
