### ISSUE TITLE
为什么储存的value类型支持Parcelable呢？

### ISSUE THREAD

**Issue by alberthgh** [Tencent/MMKV#563]
你好~
为什么MMKV支持直接把Parcelable作为value储存呢？
Android官方文档指出：”Parcel 不是通用序列化机制，您绝不能将任何 Parcel 数据存储在磁盘上或通过网络发送“。（https://developer.android.com/guide/components/activities/parcelables-and-bundles）
在项目中我在这里踩了坑。
一个bean的成员变量更新了，但是我忘了修改相关的writeToParcel和构造方法，编译和运行过程都没有出错。但是新修改的成员变量是不会有效储存和读取的。
非常建议把直接储存Parcelable对象的方法删除~

**Comment by lingol** [comment]
What Android official has said, it means they keep the right to change the underlying data structure in the future. But they have never changed a thing since Android 1.0.
As for your case, changing a class member without changing `writeToParcel()` & other relative methods, you will face errors even when you send your object to another process (in a way that Android officially support).

So, it's your fault, not MMKV's.

**Comment by alberthgh** [comment]
这个错误是我没认清Parcelable机制的情况下造成的，我没指责MMKV。
但是储存Parcelable到磁盘，的确直接违反了官方建议，即使这里只有MMKV能读取数据。
想象版本1.0有Parcelable类ParcelA.class，他有三个int变量a、b、c，在版本2.0中我要删除a变量，这种情况开发者还不能直接删除a，因为用户手中的版本1.0仍然会按abc的顺序读取数据。版本变动越多，维护越难。

**Comment by lingol** [comment]
That is not MMKV's problem. If you can't handle that complexity, you should not use it.

PS: you can just use protobuf to encode an object into bytes, then store the bytes inside MMKV. Nothing difficult.

**Comment by alberthgh** [comment]
thx~~
