### ISSUE TITLE
为什么把MMKVflutter 改成了mmkv

### ISSUE THREAD

**Issue by 9527001** [Tencent/MMKV#727]
#### 目前我们的解决方案是fork代码，把名字改回mmkvflutter。希望有更好的建议。

**Comment by lingol** [comment]
It's a requirement from Dart packages. The CocoaPod name must be the same as the Dart package name. 
I have tried and failed to find any solution.

**Comment by 9527001** [comment]
![image](https://user-images.githubusercontent.com/16686832/127474929-332c3f61-41a5-4264-8326-a8144b127434.png)

**Comment by lingol** [comment]
You don't get it. So please leave it alone.

**Comment by WeiCongcong** [comment]
我也没有get到，既然只是因为名字冲突，就索性都改了呗，总不能一直因为这么个问题，增加开发成本和引入体验吧。今天第一次用，遇到这个问题，感觉很奇怪，只谈自己浅薄的感受。

**Comment by lingol** [comment]
Okay, I will try to explain it more. 
1. The MMKV project already has a CocoaPods repo **for iOS native developers**, in the name of `MMKV`. https://cocoapods.org/pods/MMKV
2. The MMKV for Dark package is created under the name `mmkv`. https://pub.dev/packages/mmkv
3. The pod spec file inside the flutter package, aka `flutter/iOS/mmkvflutter.podspec`, is for describing the iOS project for flutter.
4. The problem is that the `Pod::Spec.name` in the pod spec file in step 3 must be the same as the Dark package name, aka `mmkv`. Otherwise, the dark package platform (https:://pub.dev) won't accept it. It's not that we don't want to change it. It's simply impossible.
5. The solution is that developer will have to run scripts to alter the name to `mmkvflutter` each time after running `pub install`.
