### ISSUE TITLE
MMKV initialize error: fail to load libmmkv.so by -4 returned

### ISSUE THREAD

**Issue by alienwings** [Tencent/MMKV#788]
### The language of MMKV

> Java/Kotlin

### The version of MMKV

> v1.2.11

### The platform of MMKV

> Android

### The installation of MMKV

> maven

### What's the issue?
       
We have met some online crashes every day caused by MMKV initializing failure, the logs are below:
`java.lang.IllegalStateException: You should Call MMKV.initialize() first.
at com.tencent.mmkv.MMKV.mmkvWithID(SourceFile:4)`

We use code below to initialize MMKV:
`       
        try {
            MMKV.initialize(context, libName -> ReLinker.loadLibrary(context, libName));
        } catch (Throwable t) {
            reportMMKVException(t);
        }
`

And we have confirmed the issue was caused by MMKV initializing failure by reporting exception using reportMMKVException() in catch block. The exception log is pasted below: 

Android version：8.0.0

Device：HUAWEILON-AL00

### What's the log of MMKV when that happened?

The UnsatisfiedLinkError throwed in catch block:

java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/com.lofter.android/app_lib/libmmkv.so": -4

The error code -4 is returned by code below, I wonder why registerNativeMethods fail? 

`
int ret = registerNativeMethods(env, g_cls);
    if (ret != 0) {
        MMKVError("fail to register native methods for class %s, ret = %d", clsName, ret);
        return -4;
    }
`

**Comment by lingol** [comment]
And what's **the exact log** MMKV print about `fail to register native methods`?

**Comment by alienwings** [comment]
Sorry, I can't reproduce it on my device since the UnsatisfiedLinkError is reported accidentally at a very small probability, so I can't get the logcat print. The only thing that can be deduced from the metioned error information is that MMKV fails to execute it's JNI_OnLoad function and return by -4 in advance. Our app has more than twenty shared libraries and we have never met other shared libraries throw that error. Do you have any advice to track this issue? Thanks.

**Comment by lingol** [comment]
You should collect and provide MMKV's log for further analysis.

**Comment by alienwings** [comment]
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/com.lofter.android/app_lib/libmmkv.so": -4

Is this log helpful?

**Comment by lingol** [comment]
Any luck on collecting MMKV's log?

**Comment by lingol** [comment]
Closed due to inactive.

**Comment by MQHuan** [comment]
I got a similar error,

**Comment by MQHuan** [comment]
01-08 14:11:12.245  3632  3678 I ActivityManager: Start proc 30499:com.skyworth.smarthotel.tv/1000 for restart com.skyworth.smarthotel.tv
01-08 14:11:12.246 30499 30499 I Zygote  : seccomp disabled by setenforce 0
01-08 14:11:12.246 30499 30499 I Zygote  : seccomp disabled by setenforce 0
01-08 14:11:12.251 30499 30499 W h.smarthotel.t: Using default instruction set featuresfor ARM CPU variant (cortex-a9) using conservative defaults
01-08 14:11:12.251 30499 30499 W h.smarthotel.t: Using default instruction set featuresfor ARM CPU variant (cortex-a9) using conservative defaults
01-08 14:11:12.254 30499 30499 E h.smarthotel.t: Not starting debugger since process cannot load the jdwp agent.
01-08 14:11:12.254 30499 30499 E h.smarthotel.t: Not starting debugger since process cannot load the jdwp agent.
01-08 14:11:12.300 30499 30499 I MMKV    : Disable checkProcessMode()
01-08 14:11:12.300 30499 30499 I MMKV    : Disable checkProcessMode()
01-08 14:11:12.303 30499 30499 E linker  : name =/system/ccos/lib/libmmkv.so,realpath=/system/ccos/lib/libmmkv.so
01-08 14:11:12.303 30499 30499 E linker  : name =/system/ccos/lib/libmmkv.so,realpath=/system/ccos/lib/libmmkv.so
01-08 14:11:12.307 30499 30499 E h.smarthotel.t: Failed to register non-native method com.tencent.mmkv.MMKV.isFileValid(Ljava/lang/String;)Z as native
01-08 14:11:12.307 30499 30499 E h.smarthotel.t: Failed to register non-native method com.tencent.mmkv.MMKV.isFileValid(Ljava/lang/String;)Z as native
01-08 14:11:12.308 30499 30499 E MMKV    : <native-bridge.cpp:74::JNI_OnLoad> fail to register native methods for class com/tencent/mmkv/MMKV, ret = -1
01-08 14:11:12.308 30499 30499 E MMKV    : <native-bridge.cpp:74::JNI_OnLoad> fail to register native methods for class com/tencent/mmkv/MMKV, ret = -1
01-08 14:11:12.308 30499 30499 D AndroidRuntime: Shutting down VM
01-08 14:11:12.308 30499 30499 D AndroidRuntime: Shutting down VM
01-08 14:11:12.310 30499 30499 E AndroidRuntime: FATAL EXCEPTION: main
01-08 14:11:12.310 30499 30499 E AndroidRuntime: FATAL EXCEPTION: main
01-08 14:11:12.310 30499 30499 E AndroidRuntime: Process: com.skyworth.smarthotel.tv, PID: 30499
01-08 14:11:12.310 30499 30499 E AndroidRuntime: Process: com.skyworth.smarthotel.tv, PID: 30499
01-08 14:11:12.310 30499 30499 E AndroidRuntime: Process: com.skyworth.smarthotel.tv, PID: 30499
01-08 14:11:12.310 30499 30499 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/system/ccos/lib/libmmkv.so": -4
01-08 14:11:12.310 30499 30499 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/system/ccos/lib/libmmkv.so": -4
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:146)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:146)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.lelight.leiot.smart.LeIoTSdk.OooO00o(Unknown Source:29)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.lelight.leiot.smart.LeIoTSdk.OooO00o(Unknown Source:29)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.lelight.leiot.smart.LeIoTSdk.initBase(Unknown Source:0)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.lelight.leiot.smart.LeIoTSdk.initBase(Unknown Source:0)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.lelight.leiot.sdk.LeHomeSdk.attachBaseContext(LeHomeSdk.java:1)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.lelight.leiot.sdk.LeHomeSdk.attachBaseContext(LeHomeSdk.java:1)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.jaytech.tvgateway.sdk.TVGatewaySDK.attachBaseContext(TVGatewaySDK.java:63)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at cn.jaytech.tvgateway.sdk.TVGatewaySDK.attachBaseContext(TVGatewaySDK.java:63)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.skyworth.smarthotel.tv.SwaiotHotelApp.attachBaseContext(SwaiotHotelApp.java:53)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.skyworth.smarthotel.tv.SwaiotHotelApp.attachBaseContext(SwaiotHotelApp.java:53)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.Application.attach(Application.java:212)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.Application.attach(Application.java:212)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5858)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5858)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:203)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:203)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6685)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6685)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:900)
01-08 14:11:12.310 30499 30499 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:900)
01-08 14:11:12.310 30499 30499 D FtraceSkyJNI: iclass, 0xbb86eb0c
01-08 14:11:12.310 30499 30499 D FtraceSkyJNI: iclass, 0xbb86eb0c
01-08 14:11:12.311 30499 30499 D FtraceSkyJNI: iclass, 0xbb86eb0c
01-08 14:11:12.311 30499 30499 D FtraceSkyJNI: iclass, 0xbb86eb0c
01-08 14:11:12.314 30499 30499 I Process : Sending signal. PID: 30499 SIG: 9
01-08 14:11:12.314 30499 30499 I Process : Sending signal. PID: 30499 SIG: 9
01-08 14:11:12.314 30499 30499 I Process : Sending signal. PID: 30499 SIG: 9
01-08 14:11:12.354  3632  4100 I ActivityManager: Process com.skyworth.smarthotel.tv (pid 30499) has died: pers PER 
01-08 14:11:12.354  3632  4100 E SkyCamera: pid=3632 uid=1000>>>>>setCameraUpDown2:-1 cameraId:-1 ListenPidKilled:30499 mCameraUpDownStatus-1 cameraSwitch:false
01-08 14:11:12.354  3632  4100 W ActivityManager: Re-adding persistent process ProcessRecord{f5cf870 30499:com.skyworth.smarthotel.tv/1000}
01-08 14:11:12.354  3270  3270 I Zygote  : Process 30499 exited due to signal (9)
01-08 14:11:12.355  3632  3679 W libprocessgroup: kill(-30499, 9) failed: No such process
01-08 14:11:12.355  3632  3679 I libprocessgroup: Successfully killed process cgroup uid 1000 pid 30499 in 0ms

**Comment by lingol** [comment]
@MQHuan You can Google about this error.
>01-08 14:11:12.307 30499 30499 E h.smarthotel.t: Failed to register non-native method com.tencent.mmkv.MMKV.isFileValid(Ljava/lang/String;)Z as native
