### ISSUE TITLE
why not add a "dstDir" parameter for restoreAllFromDirectory() API ?

### ISSUE THREAD

**Issue by Eric-Li-2356** [Tencent/MMKV#821]
### The language of MMKV

Java

### The version of MMKV

v1.2.11

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
why the restoreAllFromDirectory() API
![image](https://user-images.githubusercontent.com/55909871/150664583-1e7105bb-8997-4d3a-9ac5-ab7f6c3a045b.png)
not provide dstDir parameter used to specify the destination directory that all mmkv files will restore to? 
Just like restoreOneMMKVFromDirectory() API
![image](https://user-images.githubusercontent.com/55909871/150664637-e01e3981-e594-4ecb-be48-0dced51b0930.png)

Now the restoreAllFromDirectory() API is very inconvenient that it can only restore to root directory.

**Comment by lingol** [comment]
It's inconvenient indeed. If you happened to have a look at MMKV on other platforms (such as iOS), you will find that they support restoring other target directories. It's only Android that's limited. 

The reason is rooted deep in MMKV's early version that mistakenly names MMKV with special char(*/\, etc). And for backward compatibility, we have no choice but to limit the functionality of `restoreAll()`.

Should you be interested, the relative commit is here https://github.com/Tencent/MMKV/commit/d31b223fe6cd782f1c53093516a85e21f2f38c57#diff-80bef4c8386a4b7c2695b8bcca7273a1e304188ae1213bfeb2cd5622aa8998c6.

**Comment by lingol** [comment]
And here's the root cause https://github.com/Tencent/MMKV/commit/3df5a7b5ac6f67fdcfb3cd5d6aead1c3d6eb7e31.

**Comment by Eric-Li-2356** [comment]
ok, I'll have a look.
